In [23]:
import pandas as pd
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler

In [25]:
data=pd.read_csv(r'C:\Users\RINNY\Downloads\homeprices.csv')
print(data)

   area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000


In [27]:
x = data[['area', 'bedrooms', 'age']]
y = data['price']
print(x)
print(y)

   area  bedrooms  age
0  2600       3.0   20
1  3000       4.0   15
2  3200       NaN   18
3  3600       3.0   30
4  4000       5.0    8
5  4100       6.0    8
0    550000
1    565000
2    610000
3    595000
4    760000
5    810000
Name: price, dtype: int64


In [29]:
scalar=StandardScaler()
scalar

StandardScaler()

In [31]:
x_scalar=scalar.fit_transform(x)
print(x_scalar)

[[-1.52162173 -1.02899151  0.46257302]
 [-0.77633762 -0.17149859 -0.19824558]
 [-0.40369556         nan  0.19824558]
 [ 0.34158855 -1.02899151  1.78421022]
 [ 1.08687266  0.68599434 -1.12339162]
 [ 1.27319369  1.54348727 -1.12339162]]


In [33]:
from sklearn.model_selection import train_test_split
xtrain,ytrain,xtest,ytest=train_test_split(x_scalar,y,random_state=45)
print("the xtrain is",xtrain)
print("the ytrain is ",ytrain)
print("the xtest is ",xtest)
print("the ytest is ",ytest)


the xtrain is [[ 1.08687266  0.68599434 -1.12339162]
 [-1.52162173 -1.02899151  0.46257302]
 [ 1.27319369  1.54348727 -1.12339162]
 [ 0.34158855 -1.02899151  1.78421022]]
the ytrain is  [[-0.40369556         nan  0.19824558]
 [-0.77633762 -0.17149859 -0.19824558]]
the xtest is  4    760000
0    550000
5    810000
3    595000
Name: price, dtype: int64
the ytest is  2    610000
1    565000
Name: price, dtype: int64


In [35]:
linear_regression_model=LinearRegression()
linear_regression_model

LinearRegression()

In [37]:
linear_regression_model.fit(xtrain,xtest)

LinearRegression()

In [47]:
linear_regression_model.coef_

array([ 36675.05165068,  50340.55135883, -17654.87027549])

In [41]:
linear_regression_model.intercept_

665772.2222222222

In [60]:
pred=linear_regression_model.predict(xtrain)
prediction=np.abs(pred)
prediction

array([760000., 550000., 810000., 595000.])